version: '3'

services:
#  php5.6-apache.test:
#    container_name: php.test
#    restart: always
#    image: yousan/php5.6-apache:latest
##    build: ../damp_dockerfile/php5.6/apache/ # for develop
#    ports:
#      - 80:80
#    volumes:
#      - ./php5.6-apache-php:/tmp/php/
#      # Add symlink directories if you use symlinks at documents.
#      - ~/git:/Users/yousan/git
#      - ~/svn:/Users/yousan/svn
#      - ~/public_html:/var/www/vhosts
#    environment:
#      PMA_HOST: mysql.test
#      PMA_USER: root
#      PMA_PASSWORD: example

  php7.2-apache.test:
    container_name: php72.test
    restart: always
    image: yousan/php7.2-apache
#    build: ../damp_dockerfile/php5.6/apache/ # for develop
    ports:
      - 80:80
    volumes:
      - ./php7.2/apache/pma.test:/var/www/vhosts/pma.test
      - ./php7.2/apache/apache2:/etc/apache2
      - ./php7.2/apache/php:/usr/local/etc/php
      # Add symlink directories if you use symlinks at documents.
      - ~/git:/Users/yousan/git
      - ~/svn:/Users/yousan/svn
      - ~/public_html:/var/www/vhosts
    environment:
      PMA_HOST: mysql.test
      PMA_USER: root
      PMA_PASSWORD: example

  mysql.test:
    container_name: mysql.test
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - /private/var/lib/mysql:/var/lib/mysql

  dnsmasq.test:
    container_name: dnsmasq.test
    image: yousan/dnsmasq:1.6.1
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add:
      - NET_ADMIN
  # selenium.test:
  #   image: selenium/standalone-chrome-debug:latest
  #   ports:
  #    - 4444:4444/tcp
  #    - 5901:5900/tcp
  #   external_links:
  #    - php5.6-apache.test:zaip.test

  mailcatcher.test:
    container_name: mailcatcher.test
    image: schickling/mailcatcher
    ports:
      - 1025:1025/tcp
      - 1080:1080/tcp
